default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: instagram-challenge-2_development

test:
  <<: *default
  database: instagram-challenge-2_test

production:
  <<: *default
  database: instagram-challenge-2_production
  username: instagram-challenge-2
  password: <%= ENV['INSTAGRAM-CHALLENGE-2_DATABASE_PASSWORD'] %>
